[package]
name = "pocker"
version = "0.1.5"
edition = "2024"

[workspace]
members = ["crates/pocker-compose"]
resolver = "3"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.6.1", features = ["derive"] }
directories = "6.0.0"
futures-util = "0.3.31"
hex = "0.4.3"
http = "1.3.1"
httpdate = "1.0.3"
indicatif = "0.17.11"
percent-encoding = "2.3.2"
pocker-compose = { path = "crates/pocker-compose" }
reqwest = { version = "0.12.24", default-features = false, features = ["json", "rustls-tls", "stream"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
tar = "0.4.44"
tempfile = "3.23.0"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["fs", "io-util", "macros", "net", "process", "rt-multi-thread", "signal", "sync", "time"] }
tokio-util = { version = "0.7.18", features = ["io", "io-util"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
url = "2.5.7"

[profile.release]
strip = "symbols"
lto = "thin"
codegen-units = 1
panic = "abort"
opt-level = "z"
